devstream-io/dtm-jenkins-share-library:
  - source: staging/dtm-jenkins-share-library/
    dest: .
    deleteOrphaned: true
devstream-io/dtm-pipeline-templates:
  - source: staging/dtm-pipeline-templates/
    dest: .
    deleteOrphaned: true
devstream-io/dtm-repo-scaffolding-golang-cli:
  - source: staging/dtm-repo-scaffolding-golang-cli/
    dest: .
    deleteOrphaned: true
devstream-io/dtm-repo-scaffolding-golang-gin:
  - source: staging/dtm-repo-scaffolding-golang-gin/
    dest: .
    deleteOrphaned: true
devstream-io/dtm-repo-scaffolding-java-springboot:
  - source: staging/dtm-repo-scaffolding-java-springboot/
    dest: .
    deleteOrphaned: true
devstream-io/dtm-repo-scaffolding-python-flask:
  - source: staging/dtm-repo-scaffolding-python-flask/
    dest: .
    deleteOrphaned: true
