name: Bug Report
description: Report a bug of DevStream
title: ":bomb: `Bug`: "
labels: bug
body:
- type: textarea
  id: problem
  attributes:
    label: What happened?
    description: Please provide as much information as possible.
  validations:
    required: true

- type: textarea
  id: repro
  attributes:
    label: How to reproduce?
  validations:
    required: true

- type: textarea
  id: dtmVersion
  attributes:
    label: 'DevStream version (to find out the version run: dtm version)'
  validations:
    required: true
