name: Documentation Issue
description: Help to improve our documentation
title: ":open_book: `Docs`: "
labels: docs
body:
- type: textarea
  id: problem
  attributes:
    label: What should be changed?
    description: Please provide as much info as possible.
  validations:
    required: true
