name: Documentation Issue
description: Help to improve our documentation
title: ":open_book: `Docs`: "
labels: docs
body:
- type: textarea
  id: problem
  attributes:
    label: What should be changed?
    description: Please provide as much info as possible.
  validations:
    required: true
- type: checkboxes
  id: terms
  attributes:
    label: I've read the documents below.
    description: Please read the list of documents below if you want to submit a document type contribution.
    options:
      - label: [Creating a Documentation for DevStream](https://docs.devstream.io/en/latest/development/mkdocs/)
        required: false
      - label: [Document Translation(Chinese only)](https://docs.devstream.io/en/latest/development/translation.zh/)
        required: false
