name: Enhancement / Proposal
description: Provide supporting details for an existing or a new feature
title: ":four_leaf_clover: `Proposal`: "
labels: proposal
body:
- type: textarea
  id: proposal
  attributes:
    label: What would you like to add? Why is this needed?
    description: For feature requests, please also engage with the PMC on Slack or WeChat.
  validations:
    required: true
