[[ if .dingTalk -]]
setting.configNotifyDingtalk([
    'robot_id': "[[ .dingTalk.name ]]",
])
[[ end -]]
[[ if .imageRepo -]]
setting.configImageRepo([
    'image_repo': "[[ .imageRepo.url ]]",
    'user': "[[ .imageRepo.user ]]",
    'auth_secret_name': "[[ .ImageRepoDockerSecret ]]",
])
[[ end -]]
runPipeline([
    'name': "[[ .AppName ]]",
    [[ if .sonarqube -]]
    'sonarqube_enable': true,
    [[ end -]]
    [[ if .general -]]
    [[ if .general.language -]]
    'language': [[ .general.language ]],
    [[ end -]]
    [[ if .general.enableTest -]]
    'test_enable': [[ .general.enableTest ]],
    [[ end -]]
    [[ end -]]
])
