---
# core config
varFile: "" # If not empty, use the specified external variables config file
toolFile: "" # If not empty, use the specified external tools config file
state: # state config, backend can be local or s3
  backend: local
  options:
    stateFile: devstream.state

---
# plugins config
tools:
  - name: repo-scaffolding
    instanceID: golang-github
    options:
      destination_repo:
        owner: YOUR_GITHUB_USERNAME_CASE_SENSITIVE
        org: ""
        repo: go-webapp-devstream-demo
        branch: main
        repo_type: github
      source_repo:
        org: devstream-io
        repo: dtm-scaffolding-golang
        repo_type: github
      vars:
        ImageRepo: YOUR_DOCKER_USERNAME/go-webapp-devstream-demo
  - name: githubactions-golang
    instanceID: default
    dependsOn: ["repo-scaffolding.golang-github"]
    options:
      owner: YOUR_GITHUB_USERNAME_CASE_SENSITIVE
      repo: go-webapp-devstream-demo
      language:
        name: go
        version: "1.18"
      branch: main
      build:
        enable: True
      test:
        enable: True
        coverage:
          enable: True
      docker:
        enable: False
