name: main Builder

on:
  push:
    branches: [ main ]

jobs:

  test:
      name: Test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.17
        - name: Build
          run: make build
        - name: Test
          run: go test -v ./...
        - name: Staticcheck
          run: |
            # add executables installed with go get to PATH
            # TODO: this will hopefully be fixed by
            # https://github.com/actions/setup-go/issues/14
            export PATH=${PATH}:`go env GOPATH`/bin
            go get -u honnef.co/go/tools/cmd/staticcheck
            staticcheck ./... 
